package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
)

func main() {

	type opCodesMatrix struct {
		Op string // OpCode
		Mn string // Mnemonic
		Ol int    // OpCodeLength
	}
	opCodesJson := `[
{"op":"00", "mn":"NOP", "ol":0},
{"op":"01", "mn":"ILL", "ol":3},
{"op":"02", "mn":"OUTL BUS,A", "ol":0},
{"op":"03", "mn":"ADD A,#", "ol":1},
{"op":"04", "mn":"JMP $0", "ol":1},
{"op":"05", "mn":"EN I", "ol":0},
{"op":"06", "mn":"ILL", "ol":3},
{"op":"07", "mn":"DEC A", "ol":0},
{"op":"08", "mn":"INS A,BUS", "ol":0},
{"op":"09", "mn":"IN A,P1", "ol":0},
{"op":"0a", "mn":"IN A,P2", "ol":0},
{"op":"0b", "mn":"ILL", "ol":3},
{"op":"0c", "mn":"MOVD A,P4", "ol":0},
{"op":"0d", "mn":"MOVD A,P5", "ol":0},
{"op":"0e", "mn":"MOVD A,P6", "ol":0},
{"op":"0f", "mn":"MOVD A,P7", "ol":0},
{"op":"10", "mn":"INC @R0", "ol":0},
{"op":"11", "mn":"INC @R1", "ol":0},
{"op":"12", "mn":"JB0 $", "ol":1},
{"op":"13", "mn":"ADDC A,#", "ol":1},
{"op":"14", "mn":"CALL $", "ol":1},
{"op":"15", "mn":"DIS I", "ol":0},
{"op":"16", "mn":"JTF $", "ol":1},
{"op":"17", "mn":"INC A", "ol":0},
{"op":"18", "mn":"INC R0", "ol":0},
{"op":"19", "mn":"INC R1", "ol":0},
{"op":"1a", "mn":"INC R2", "ol":0},
{"op":"1b", "mn":"INC R3", "ol":0},
{"op":"1c", "mn":"INC R4", "ol":0},
{"op":"1d", "mn":"INC R5", "ol":0},
{"op":"1e", "mn":"INC R6", "ol":0},
{"op":"1f", "mn":"INC R7", "ol":0},
{"op":"20", "mn":"XCH A,@R0", "ol":0},
{"op":"21", "mn":"XCH A,@R1", "ol":0},
{"op":"22", "mn":"ILL", "ol":3},
{"op":"23", "mn":"MOV A,#", "ol":1},
{"op":"24", "mn":"JMP $1", "ol":1},
{"op":"25", "mn":"EN TCNTI", "ol":0},
{"op":"26", "mn":"JNT0 $", "ol":1},
{"op":"27", "mn":"CLR A", "ol":0},
{"op":"28", "mn":"XCH A,R0", "ol":0},
{"op":"29", "mn":"XCH A,R1", "ol":0},
{"op":"2a", "mn":"XCH A,R2", "ol":0},
{"op":"2b", "mn":"XCH A,R3", "ol":0},
{"op":"2c", "mn":"XCH A,R4", "ol":0},
{"op":"2d", "mn":"XCH A,R5", "ol":0},
{"op":"2e", "mn":"XCH A,R6", "ol":0},
{"op":"2f", "mn":"XCH A,R7", "ol":0},
{"op":"30", "mn":"XCHD A,@R0", "ol":0},
{"op":"31", "mn":"XCHD A,@R1", "ol":0},
{"op":"32", "mn":"JB1 $", "ol":1},
{"op":"33", "mn":"ILL", "ol":0},
{"op":"34", "mn":"CALL $", "ol":1},
{"op":"35", "mn":"DIS TCNTI", "ol":0},
{"op":"36", "mn":"JT0 $", "ol":1},
{"op":"37", "mn":"CPL A", "ol":0},
{"op":"38", "mn":"ILL", "ol":3},
{"op":"39", "mn":"OUTL P1,A", "ol":0},
{"op":"3a", "mn":"OUTL P2,A", "ol":0},
{"op":"3b", "mn":"ILL", "ol":0},
{"op":"3c", "mn":"MOVD P4,A", "ol":2},
{"op":"3d", "mn":"MOVD P5,A", "ol":0},
{"op":"3e", "mn":"MOVD P6,A", "ol":0},
{"op":"3f", "mn":"MOVD P7,A", "ol":0},
{"op":"40", "mn":"ORL A,@R0", "ol":0},
{"op":"41", "mn":"ORL A,@R1", "ol":0},
{"op":"42", "mn":"MOV A,T", "ol":0},
{"op":"43", "mn":"ORL A,#", "ol":1},
{"op":"44", "mn":"JMP $2", "ol":1},
{"op":"45", "mn":"STRT CNT", "ol":0},
{"op":"46", "mn":"JNT1 $", "ol":1},
{"op":"47", "mn":"SWAP", "ol":0},
{"op":"48", "mn":"ORL A,R0", "ol":0},
{"op":"49", "mn":"ORL A,R1", "ol":0},
{"op":"4a", "mn":"ORL A,R2", "ol":0},
{"op":"4b", "mn":"ORL A,R3", "ol":0},
{"op":"4c", "mn":"ORL A,R4", "ol":0},
{"op":"4d", "mn":"ORL A,R5", "ol":0},
{"op":"4e", "mn":"ORL A,R6", "ol":0},
{"op":"4f", "mn":"ORL A,R7", "ol":0},
{"op":"50", "mn":"ANL A,@R0", "ol":0},
{"op":"51", "mn":"ANL A,@R1", "ol":0},
{"op":"52", "mn":"JB2 $", "ol":1},
{"op":"53", "mn":"ANL A,#", "ol":1},
{"op":"54", "mn":"CALL $", "ol":1},
{"op":"55", "mn":"STRT T", "ol":0},
{"op":"56", "mn":"JT1 $", "ol":1},
{"op":"57", "mn":"ILL", "ol":3},
{"op":"58", "mn":"ANL A,R0", "ol":0},
{"op":"59", "mn":"ANL A,R1", "ol":0},
{"op":"5a", "mn":"ANL A,R2", "ol":0},
{"op":"5b", "mn":"ANL A,R3", "ol":0},
{"op":"5c", "mn":"ANL A,R4", "ol":0},
{"op":"5d", "mn":"ANL A,R5", "ol":0},
{"op":"5e", "mn":"ANL A,R6", "ol":0},
{"op":"5f", "mn":"ANL A,R7", "ol":0},
{"op":"60", "mn":"ADD A,@R0", "ol":0},
{"op":"61", "mn":"ADD A,@R1", "ol":0},
{"op":"62", "mn":"MOV T,A", "ol":0},
{"op":"63", "mn":"ILL", "ol":3},
{"op":"64", "mn":"JMP $3", "ol":1},
{"op":"65", "mn":"STOP TCNT", "ol":0},
{"op":"66", "mn":"ILL", "ol":3},
{"op":"67", "mn":"RRC A", "ol":0},
{"op":"68", "mn":"ADD A,R0", "ol":0},
{"op":"69", "mn":"ADD A,R1", "ol":0},
{"op":"6a", "mn":"ADD A,R2", "ol":0},
{"op":"6b", "mn":"ADD A,R3", "ol":0},
{"op":"6c", "mn":"ADD A,R4", "ol":0},
{"op":"6d", "mn":"ADD A,R5", "ol":0},
{"op":"6e", "mn":"ADD A,R6", "ol":0},
{"op":"6f", "mn":"ADD A,R7", "ol":0},
{"op":"70", "mn":"ADDC A,@R0", "ol":0},
{"op":"71", "mn":"ADDC A,@R1", "ol":0},
{"op":"72", "mn":"JB3 $", "ol":1},
{"op":"73", "mn":"ILL", "ol":3},
{"op":"74", "mn":"CALL $", "ol":1},
{"op":"75", "mn":"ENT0 CLK", "ol":0},
{"op":"76", "mn":"JF1 $ ", "ol":1},
{"op":"77", "mn":"RR A", "ol":0},
{"op":"78", "mn":"ADDC A,R0", "ol":0},
{"op":"79", "mn":"ADDC A,R1", "ol":0},
{"op":"7a", "mn":"ADDC A,R2", "ol":0},
{"op":"7b", "mn":"ADDC A,R3", "ol":0},
{"op":"7c", "mn":"ADDC A,R4", "ol":0},
{"op":"7d", "mn":"ADDC A,R5", "ol":0},
{"op":"7e", "mn":"ADDC A,R6", "ol":0},
{"op":"7f", "mn":"ADDC A,R7", "ol":0},
{"op":"80", "mn":"MOVX A,@R0", "ol":0},
{"op":"81", "mn":"MOVX A,@R1", "ol":0},
{"op":"82", "mn":"ILL", "ol":0},
{"op":"83", "mn":"RET", "ol":0},
{"op":"84", "mn":"JMP $4", "ol":1},
{"op":"85", "mn":"CLR F0", "ol":0},
{"op":"86", "mn":"JNI $", "ol":1},
{"op":"87", "mn":"ILL", "ol":3},
{"op":"88", "mn":"ORL BUS,#", "ol":1},
{"op":"89", "mn":"ORL P1,#", "ol":1},
{"op":"8a", "mn":"ORL P2,#", "ol":1},
{"op":"8b", "mn":"ILL", "ol":3},
{"op":"8c", "mn":"ORLD P4,A", "ol":0},
{"op":"8d", "mn":"ORLD P5,A", "ol":0},
{"op":"8e", "mn":"ORLD P6,A", "ol":0},
{"op":"8f", "mn":"ORLD P7,A", "ol":0},
{"op":"90", "mn":"MOVX @R0,A", "ol":0},
{"op":"91", "mn":"MOVX @R1,A", "ol":0},
{"op":"92", "mn":"JB4 $", "ol":1},
{"op":"93", "mn":"RETR", "ol":0},
{"op":"94", "mn":"CALL $", "ol":1},
{"op":"95", "mn":"CPL F0", "ol":0},
{"op":"96", "mn":"JNZ $", "ol":1},
{"op":"97", "mn":"CLR C", "ol":0},
{"op":"98", "mn":"ANL BUS,#", "ol":1},
{"op":"99", "mn":"ANL P1,#", "ol":1},
{"op":"9a", "mn":"ANL P2,#", "ol":1},
{"op":"9b", "mn":"ILL", "ol":3},
{"op":"9c", "mn":"ANLD P4,A", "ol":0},
{"op":"9d", "mn":"ANLD P5,A", "ol":0},
{"op":"9e", "mn":"ANLD P6,A", "ol":0},
{"op":"9f", "mn":"ANLD P7,A", "ol":0},
{"op":"a0", "mn":"MOV @R0,A", "ol":0},
{"op":"a1", "mn":"MOV @R1,A", "ol":0},
{"op":"a2", "mn":"ILL", "ol":3},
{"op":"a3", "mn":"MOVP A,@A", "ol":0},
{"op":"a4", "mn":"JMP $5", "ol":1},
{"op":"a5", "mn":"CLR F1", "ol":0},
{"op":"a6", "mn":"ILL", "ol":3},
{"op":"a7", "mn":"CPL C", "ol":0},
{"op":"a8", "mn":"MOV R0,A", "ol":0},
{"op":"a9", "mn":"MOV R1,A", "ol":0},
{"op":"aa", "mn":"MOV R2,A", "ol":0},
{"op":"ab", "mn":"MOV R3,A", "ol":0},
{"op":"ac", "mn":"MOV R4,A", "ol":0},
{"op":"ad", "mn":"MOV R5,A", "ol":0},
{"op":"ae", "mn":"MOV R6,A", "ol":0},
{"op":"af", "mn":"MOV R7,A", "ol":0},
{"op":"b0", "mn":"MOV @R0,#", "ol":1},
{"op":"b1", "mn":"MOV @R1,#", "ol":1},
{"op":"b2", "mn":"JB5 $", "ol":1},
{"op":"b3", "mn":"JMPP @A", "ol":0},
{"op":"b4", "mn":"CALL $", "ol":1},
{"op":"b5", "mn":"CPL F1", "ol":0},
{"op":"b6", "mn":"JF0 $", "ol":1},
{"op":"b7", "mn":"ILL", "ol":3},
{"op":"b8", "mn":"MOV R0,#", "ol":1},
{"op":"b9", "mn":"MOV R1,#", "ol":1},
{"op":"ba", "mn":"MOV R2,#", "ol":1},
{"op":"bb", "mn":"MOV R3,#", "ol":1},
{"op":"bc", "mn":"MOV R4,#", "ol":1},
{"op":"bd", "mn":"MOV R5,#", "ol":1},
{"op":"be", "mn":"MOV R6,#", "ol":1},
{"op":"bf", "mn":"MOV R7,#", "ol":1},
{"op":"c0", "mn":"ILL", "ol":3},
{"op":"c1", "mn":"ILL", "ol":3},
{"op":"c2", "mn":"ILL", "ol":3},
{"op":"c3", "mn":"ILL", "ol":3},
{"op":"c4", "mn":"JMP $6", "ol":1},
{"op":"c5", "mn":"SEL RB0", "ol":0},
{"op":"c6", "mn":"JZ $", "ol":1},
{"op":"c7", "mn":"MOV A,PSW", "ol":0},
{"op":"c8", "mn":"DEC R0", "ol":0},
{"op":"c9", "mn":"DEC R1", "ol":0},
{"op":"ca", "mn":"DEC R2", "ol":0},
{"op":"cb", "mn":"DEC R3", "ol":0},
{"op":"cc", "mn":"DEC R4", "ol":0},
{"op":"cd", "mn":"DEC R5", "ol":0},
{"op":"ce", "mn":"DEC R6", "ol":0},
{"op":"cf", "mn":"DEC R7", "ol":0},
{"op":"d0", "mn":"XRL A,@R0", "ol":0},
{"op":"d1", "mn":"XRL A,@R1", "ol":0},
{"op":"d2", "mn":"JB6 $", "ol":1},
{"op":"d3", "mn":"XRL A,#", "ol":1},
{"op":"d4", "mn":"CALL $", "ol":1},
{"op":"d5", "mn":"SEL RB1", "ol":1},
{"op":"d6", "mn":"ILL", "ol":3},
{"op":"d7", "mn":"MOV PSW,A", "ol":0},
{"op":"d8", "mn":"XRL A,R0", "ol":0},
{"op":"d9", "mn":"XRL A,R1", "ol":0},
{"op":"da", "mn":"XRL A,R2", "ol":0},
{"op":"db", "mn":"XRL A,R3", "ol":0},
{"op":"dc", "mn":"XRL A,R4", "ol":0},
{"op":"dd", "mn":"XRL A,R5", "ol":0},
{"op":"de", "mn":"XRL A,R6", "ol":0},
{"op":"df", "mn":"XRL A,R7", "ol":0},
{"op":"e0", "mn":"ILL", "ol":3},
{"op":"e1", "mn":"ILL", "ol":3},
{"op":"e2", "mn":"ILL", "ol":3},
{"op":"e3", "mn":"MOVP3 A,@A", "ol":0},
{"op":"e4", "mn":"JMP $7", "ol":1},
{"op":"e5", "mn":"SEL MB0", "ol":0},
{"op":"e6", "mn":"JNC $", "ol":1},
{"op":"e7", "mn":"RL A", "ol":0},
{"op":"e8", "mn":"DJNZ R0,$", "ol":1},
{"op":"e9", "mn":"DJNZ R1,$", "ol":1},
{"op":"ea", "mn":"DJNZ R2,$", "ol":1},
{"op":"eb", "mn":"DJNZ R3,$", "ol":1},
{"op":"ec", "mn":"DJNZ R4,$", "ol":1},
{"op":"ed", "mn":"DJNZ R5,$", "ol":1},
{"op":"ee", "mn":"DJNZ R6,$", "ol":1},
{"op":"ef", "mn":"DJNZ R7,$", "ol":1},
{"op":"f0", "mn":"MOV A,@R0", "ol":0},
{"op":"f1", "mn":"MOV A,@R1", "ol":0},
{"op":"f2", "mn":"JB7 $", "ol":1},
{"op":"f3", "mn":"ILL", "ol":3},
{"op":"f4", "mn":"CALL $", "ol":1},
{"op":"f5", "mn":"SEL MB1", "ol":0},
{"op":"f6", "mn":"JC $", "ol":1},
{"op":"f7", "mn":"RLC A", "ol":0},
{"op":"f8", "mn":"MOV A,R0", "ol":0},
{"op":"f9", "mn":"MOV A,R1", "ol":0},
{"op":"fa", "mn":"MOV A,R2", "ol":0},
{"op":"fb", "mn":"MOV A,R3", "ol":0},
{"op":"fc", "mn":"MOV A,R4", "ol":0},
{"op":"fd", "mn":"MOV A,R5", "ol":0},
{"op":"fe", "mn":"MOV A,R6", "ol":0},
{"op":"ff", "mn":"MOV A,R7", "ol":0}
]`

	var opCodes []opCodesMatrix
	json.Unmarshal([]byte(opCodesJson), &opCodes)
	fmt.Printf("OpCodeMatrix : %+v\n", opCodes)
	myOpCode := opCodes[1]
	fmt.Println(myOpCode.Op, myOpCode.Mn, myOpCode.Ol)

	binary := readInputFile2()

	for index := 0; index <= len(binary)-1; index++ {
		opCode := binary[index]
		fmt.Println(opCodesJson[opCode])
	}
}

func readInputFile2() []byte {
	binaryFileName := os.Args[1]
	fmt.Println(binaryFileName)

	binary, err := ioutil.ReadFile(binaryFileName)
	check2(err)

	return binary
}

func check2(e error) {
	if e != nil {
		panic(e)
	}
}
